package ee.smit.mushroom_map.entity;

import org.locationtech.jts.geom.Point;
import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a mushroom location as it's stored in our database.
 * This is the actual data model for a "location" table in the database.
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "location")
@Entity
public class LocationEntity {

    /**
     * The unique identifier for each mushroom location.
     * It's automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "location_id_generator")
    @SequenceGenerator(name="location_id_generator", sequenceName = "location_seq", allocationSize=1)
    private Long id;

    /**
     * A text description of what kind of mushrooms are found at this location.
     * This field cannot be empty in the database.
     */
    @Column(nullable = false)
    private String description;

    /**
     * The geographical point (coordinates) of the mushroom location.
     * We use a special database type "geometry(Point, 4326)" for storing map points.
     */
    @Column(columnDefinition = "geometry(Point, 4326)")
    private Point geom;
}